USE `RecaudosPagos`;
DROP procedure IF EXISTS `SP_CONSULTA_SOCIEDAD`;
SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_CONSULTA_SOCIEDAD`(
IN_COD_BANCO VARCHAR(4),
IN_CONVENIO VARCHAR(8)
)
BEGIN

	SELECT DISTINCT SOCIEDAD
	FROM Parametros 
	WHERE Parametros.COD_BANCO = IN_COD_BANCO
    AND Parametros.CONVENIO = IN_CONVENIO;
    
END$$

DELIMITER ;

