USE `RecaudosPagos`;
DROP PROCEDURE IF EXISTS `SP_CONSULTA_MOVIMIENTOS`;
SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_CONSULTA_MOVIMIENTOS`(
IN_FechaDesde VARCHAR(10),
IN_FechaHasta VARCHAR(10),
IN_CLAVE VARCHAR(20)
)
BEGIN
	SELECT
		Rec.COD_CONFIRMA_RECAUDO '#Rec', Rec.CONVENIO, CAST(Rec.FEC_RECAUDO AS DATE) 'FECHA RECAUDO',CAST(Rec.HORA_RECAUDO AS TIME) HORA,
		CAST(AES_DECRYPT(Rec.NIT_PAGADOR, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) NIT_PAGADOR,
		CAST(AES_DECRYPT(IFNULL(Rec.SOLICITANTE,Cl.NIT), IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) SOLICITANTE,
		CAST(AES_DECRYPT(Cl.Cliente, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) PRINCIPAL,
		FORMAT(CAST(AES_DECRYPT(Rec.VALOR_RECAUDADO, IN_CLAVE) AS DECIMAL),2) VALOR,
		Rec.ESTADO_RECAUDO
	FROM Recaudos Rec
	INNER JOIN Parametros Param ON Rec.COD_BANCO = Param.COD_BANCO AND Rec.CONVENIO = Param.CONVENIO
	INNER JOIN Clientes Cl ON Cl.NIT = Rec.NIT_PAGADOR AND Cl.Sociedad = Param.Sociedad OR IFNULL(Rec.Solicitante, Cl.Cliente) = Cl.Cliente AND IFNULL(Cl.NIT, Rec.Solicitante) = Cl.Cliente
	WHERE CAST(Rec.FEC_RECAUDO AS DATE) BETWEEN CAST(IN_FechaDesde AS DATE) AND CAST(IN_FechaHasta AS DATE)
	ORDER BY Rec.RECAUDO_ID DESC;
END$$

DELIMITER ;
