USE `RecaudosPagos`;
DROP procedure IF EXISTS `SP_VALIDA_RECAUDO_DUPLICADO`;
SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_VALIDA_RECAUDO_DUPLICADO`(
IN_COD_BANCO VARCHAR(4),
IN_NIT_PAGADOR VARCHAR(16),
IN_FEC_RECAUDO DATETIME,
IN_VALOR_RECAUDADO DECIMAL(16,2),
IN_COD_CONFIRMA_RECAUDO VARCHAR(16),
IN_NUM_CHEQUE VARCHAR(9),
IN_CLAVE VARCHAR(20)
)
BEGIN

	SELECT Recaudos.RECAUDO_ID
	FROM Recaudos 
	WHERE Recaudos.COD_BANCO = IN_COD_BANCO
    AND Recaudos.NIT_PAGADOR = AES_ENCRYPT(IN_NIT_PAGADOR, IN_CLAVE)
    AND Recaudos.FEC_RECAUDO = IN_FEC_RECAUDO
    AND Recaudos.VALOR_RECAUDADO = AES_ENCRYPT(IN_VALOR_RECAUDADO, IN_CLAVE)
    AND Recaudos.COD_CONFIRMA_RECAUDO = IN_COD_CONFIRMA_RECAUDO
	AND Recaudos.NUM_CHEQUE = IN_NUM_CHEQUE;
    
END$$

DELIMITER ;
