USE `RecaudosPagos`;
DROP PROCEDURE IF EXISTS `SP_CONSULTA_CLIENTES`;
SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_CONSULTA_CLIENTES`(
IN_CLAVE VARCHAR(20)
)
BEGIN
	SELECT DISTINCT
		Sociedad, 
        CAST(AES_DECRYPT(NIT, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) NIT, 
        CAST(AES_DECRYPT(Cliente, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) Cliente, 
        CAST(AES_DECRYPT(Central, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) Central
	FROM Clientes C
    ORDER BY Cliente,Sociedad;
END$$

DELIMITER ;
