USE `RecaudosPagos`;
DROP procedure IF EXISTS `SP_MODIFICA_RECAUDO_REPROCESAR`;
SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_MODIFICA_RECAUDO_REPROCESAR`(
IN_Recaudo_ID BIGINT,
IN_ESTADO_RECAUDO VARCHAR(2)
)
BEGIN

	UPDATE Recaudos
    SET ESTADO_RECAUDO = IN_ESTADO_RECAUDO
	WHERE RECAUDO_ID = IN_Recaudo_ID;

END$$

DELIMITER ;
