USE `RecaudosPagos`;
DROP procedure IF EXISTS `SP_CONSULTA_RECAUDOS_AUDITORIA`;
SET NOCOUNT ON
DELIMITER $$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_CONSULTA_RECAUDOS_AUDITORIA`(
IN_CLAVE VARCHAR(20)
)
BEGIN
	SET @orden = 0;
    SET @Recaudo_ID = 0;
	SELECT 
		CAST(IFNULL(Au.Auditoria_ID,0) AS CHAR(11)) AS Auditoria_ID, CAST(Rec.RECAUDO_ID AS CHAR(11)) AS Recaudo_ID,
		Rec.COD_BANCO, Rec.CONVENIO, Rec.COD_IAC, Rec.OFI_RECAUDO, Rec.JORNADA_PAGO, Rec.TERMI_RECAUDO, Rec.TIPO_CANJE, Rec.MONEDA, Rec.FORMA_PAGO, Rec.NUM_CHEQUE, 
		CAST(Rec.FEC_RECAUDO AS CHAR(11)) AS FEC_RECAUDO, CAST(Rec.HORA_RECAUDO AS CHAR(11)) AS HORA_RECAUDO, Rec.COD_CONFIRMA_RECAUDO, 
        CAST(AES_DECRYPT(Rec.NIT_PAGADOR, IN_CLAVE) AS CHAR(100) CHARACTER SET utf8) NIT_PAGADOR,
		CAST(AES_DECRYPT(Rec.SOLICITANTE, IN_CLAVE) AS CHAR(1000) CHARACTER SET utf8) SOLICITANTE, 
		CAST(AES_DECRYPT(Rec.VALOR_CHEQUE, IN_CLAVE) AS CHAR(1000) CHARACTER SET utf8) VALOR_CHEQUE, 
		CAST(AES_DECRYPT(Rec.VALOR_EFECTIVO, IN_CLAVE) AS CHAR(1000) CHARACTER SET utf8) VALOR_EFECTIVO, 
		CAST(AES_DECRYPT(Rec.VAL_FACTURA, IN_CLAVE) AS CHAR(1000) CHARACTER SET utf8) VAL_FACTURA, 
		CAST(AES_DECRYPT(Rec.VALOR_RECAUDADO, IN_CLAVE) AS CHAR(1000) CHARACTER SET utf8) VALOR_RECAUDADO, 
		Rec.TRANSACCION, Rec.ESTADO_RECAUDO,CONCAT(Est.Codigo,':',Est.EstadoRecaudo) AS EstadoRecaudo, 
        Au.Solicitud, Au.Respuesta, Au.Fecha, Au.Estado
	FROM Recaudos Rec
	INNER JOIN Estado_Recaudo Est ON TRIM(LEADING '0' FROM Rec.ESTADO_RECAUDO) = TRIM(LEADING '0' FROM Est.Codigo)
	LEFT JOIN (SELECT DISTINCT
				Auditoria_ID,Recaudo_ID,Estado,Solicitud,Respuesta,Fecha,Procesado,Fecha_Procesado,Usuario_Procesado,Numero
				FROM ( SELECT 
					Auditoria_ID,Estado,Solicitud,Respuesta,Fecha,Procesado,Fecha_Procesado,Usuario_Procesado,
					@orden := IF( @Recaudo_ID = Recaudo_ID, @orden + 1, 1) AS Numero,
					@Recaudo_ID := Recaudo_ID AS Recaudo_ID
					FROM Auditoria
					ORDER BY Recaudo_ID, Auditoria_ID DESC
					) Auditorias
				WHERE Numero = 1 AND (Procesado != 1 OR Procesado IS NULL))  Au ON  Rec.RECAUDO_ID = Au.Recaudo_ID
	WHERE TRIM(LEADING '0' FROM Est.Codigo ) NOT IN ('2','5') 
	ORDER BY Rec.FEC_RECAUDO ;
    
END$$
DELIMITER ;
