USE `RecaudosPagos`;

DROP procedure IF EXISTS `SP_INSERTA_RECAUDO`;

SET NOCOUNT ON
DELIMITER $$
USE `RecaudosPagos`$$
CREATE DEFINER=`RecaudosPagos`@`%` PROCEDURE `SP_INSERTA_RECAUDO`(
IN_CANAL_RECAUDO VARCHAR(2),
IN_COD_BANCO VARCHAR(4),
IN_COD_CONFIRMA_RECAUDO VARCHAR(16),
IN_COD_IAC VARCHAR(13),
IN_FEC_RECAUDO DATETIME,
IN_FEC_VENCIMIENTO DATETIME,
IN_FORMA_PAGO VARCHAR(1),
IN_HORA_RECAUDO varchar(10),
IN_JORNADA_PAGO VARCHAR(1),
IN_NUM_CHEQUE VARCHAR(9),
IN_CONVENIO VARCHAR(8),
IN_OFI_RECAUDO VARCHAR(6),
IN_NIT_PAGADOR VARCHAR(16),
IN_SOLICITANTE VARCHAR(16),
IN_TERMI_RECAUDO VARCHAR(6),
IN_TIPO_CANJE VARCHAR(1),
IN_MONEDA VARCHAR(3),
IN_VALOR_CHEQUE DECIMAL(16,2),
IN_VALOR_EFECTIVO DECIMAL(16,2),
IN_VAL_FACTURA DECIMAL(16,2),
IN_VALOR_RECAUDADO DECIMAL(16,2),
IN_TRANSACCION VARCHAR(1),
IN_ESTADO_RECAUDO VARCHAR(2),
IN_CLAVE VARCHAR(20)
)
BEGIN
	INSERT INTO Recaudos (
		CANAL_RECAUDO ,COD_BANCO,COD_CONFIRMA_RECAUDO,COD_IAC,FEC_RECAUDO,FEC_VENCIMIENTO,FORMA_PAGO,
		HORA_RECAUDO,JORNADA_PAGO,NUM_CHEQUE,CONVENIO,OFI_RECAUDO,NIT_PAGADOR,SOLICITANTE,TERMI_RECAUDO,
        TIPO_CANJE,MONEDA,VALOR_CHEQUE,VALOR_EFECTIVO,VAL_FACTURA,VALOR_RECAUDADO,TRANSACCION,ESTADO_RECAUDO)
    VALUES (
		IN_CANAL_RECAUDO,IN_COD_BANCO,IN_COD_CONFIRMA_RECAUDO,IN_COD_IAC,IN_FEC_RECAUDO,IN_FEC_VENCIMIENTO,IN_FORMA_PAGO,
		TIME(IN_HORA_RECAUDO),IN_JORNADA_PAGO,IN_NUM_CHEQUE,IN_CONVENIO,IN_OFI_RECAUDO,AES_ENCRYPT(IN_NIT_PAGADOR, IN_CLAVE),AES_ENCRYPT(IN_SOLICITANTE, IN_CLAVE),IN_TERMI_RECAUDO,
        IN_TIPO_CANJE,IN_MONEDA,AES_ENCRYPT(IN_VALOR_CHEQUE, IN_CLAVE),AES_ENCRYPT(IN_VALOR_EFECTIVO, IN_CLAVE),AES_ENCRYPT(IN_VAL_FACTURA, IN_CLAVE),AES_ENCRYPT(IN_VALOR_RECAUDADO, IN_CLAVE),IN_TRANSACCION,IN_ESTADO_RECAUDO);
		
	SELECT @@IDENTITY;
END$$

DELIMITER ;
