trigger:
- develop

resources:
  repositories:
    - repository: Templates
      type: git
      name: Templates/Templates
      ref: 'refs/heads/master'

stages:
  - template: master-corona.yml@Templates
    parameters:
      
      variables:
      - group: RecaudosPagos-QA
      
      # CI
      technology: 'netcore'
      connectionSonar: Sonar_Corona
      sonarProjectKey: RecaudosServicioBanco
      sonarProjectName: RecaudosServicioBanco
      sonarPathCoverage: '**/jacocoTestReport.xml'
      sonarExecution: 'false'
      
      # CD
      imageName: imgserviciobancodevops
      containerRegistryName: dev_recaudos_pagos_corona_registry
      tag: $(build.buildId)
      azureSubscription:  dev_recaudos_pagos_corona_qa
      appFunctionName: 'RecaudosPagosCorona'
      containerRegistryURL: crrecaudospagoscorona.azurecr.io

      # CD PROD
      containerRegistryName_Prod: prd_recaudos_pagos_corona_registry
      tag_Prod: $(build.buildId)
      imageName_Prod: imgserviciobancodevopsprd
      azureSubscription_Prod:  'prd_recaudos_pagos_corona'
      appContainerFunctionName_Prod: 'ServicioRecaudosPagosCorona'
      containerRegistryURL_Prod: crrecaudospagoscoronaprd.azurecr.io
            
      # parametros para deploy
      artifactDocker: true #Condicion de IF para saber si se realiza Docker Push
      cloud: 'azure' # parametro para iniciar CD de Azure con Docker para implementar
      deployType: 'docker'
      repoName: 'CC00-RecaudosServicioBanco-NetCore' #NO! tocar, solo equipo DevSecOps
      serviceName: 'service' #NO! tocar, solo equipo DevSecOps
      projectName: 'recaudos'