trigger:
- develop

resources:
  repositories:
    - repository: Templates
      type: git
      name: CC00-RecaudosServicioBanco-NetCore/Templates
      ref: 'refs/heads/master'

stages:
  - template: master-corona.yml@Templates
    parameters:
      tecnologia: 'netcore'
      nombreImagen: imgserviciobancodevops
      conexionSonar: Sonar_Corona
      sonarProjectKey: RecaudosServicioBanco
      sonarProjectName: RecaudosServicioBanco
      containerRegistryName: Dev_Recaudos_Pagos_Corona_Registry
      tag: ServicioBanco
            
      # parametros para deploy
      artifactDocker: true #Condicion de IF para saber si se realiza Docker Push
      cloud: 'azure' # parametro para iniciar CD de Azure con Docker para implementar
      deployType: 'docker'
      repoName: 'CC00-RecaudosServicioBanco-NetCore' #NO! tocar, solo equipo DevSecOps
      serviceName: 'service' #NO! tocar, solo equipo DevSecOps
      projectName: 'recaudos'