trigger:
- develop

pool:
  vmImage: ubuntu-latest

# Variables
variables:
  nombreImagen: imgserviciobancodevops

steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Sonar_Corona'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'RecaudosServicioBanco'
      cliProjectName: 'RecaudosServicioBanco'
      cliSources: '.'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--output publish_output --configuration Release'
  - task: SonarQubeAnalyze@4

  - task: sonar-buildbreaker@8
    inputs:
      SonarQube: 'Sonar_Corona'

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'

  - task: ArchiveFiles@2
    inputs: 
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: UseDotNet@2 
    displayName: "Instalar .NET Core 5.x"
    inputs:
      version: '5.x'

  - task: Docker@2
    inputs:
      containerRegistry: 'Dev_Recaudos_Pagos_Corona_Registry'
      repository: $(nombreImagen)
      # command: 'buildAndPush'
      # Dockerfile: '**/Dockerfile'

