//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona.RecaudoPagos.DM.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcedimientosAlmacenados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcedimientosAlmacenados() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corona.RecaudoPagos.DM.Resources.ProcedimientosAlmacenados", typeof(ProcedimientosAlmacenados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_CONSULTA_CLIENTE.
        /// </summary>
        internal static string SP_CONSULTA_CLIENTE {
            get {
                return ResourceManager.GetString("SP_CONSULTA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_CONSULTA_SOCIEDAD.
        /// </summary>
        internal static string SP_CONSULTA_SOCIEDAD {
            get {
                return ResourceManager.GetString("SP_CONSULTA_SOCIEDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_CONSULTA_USUARIO_ACCESO.
        /// </summary>
        internal static string SP_CONSULTA_USUARIO_ACCESO {
            get {
                return ResourceManager.GetString("SP_CONSULTA_USUARIO_ACCESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_INSERTA_AUDITORIA.
        /// </summary>
        internal static string SP_INSERTA_AUDITORIA {
            get {
                return ResourceManager.GetString("SP_INSERTA_AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_INSERTA_CLIENTE.
        /// </summary>
        internal static string SP_INSERTA_CLIENTE {
            get {
                return ResourceManager.GetString("SP_INSERTA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_INSERTA_RECAUDO.
        /// </summary>
        internal static string SP_INSERTA_RECAUDO {
            get {
                return ResourceManager.GetString("SP_INSERTA_RECAUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_VALIDA_RECAUDO_DUPLICADO.
        /// </summary>
        internal static string SP_VALIDA_RECAUDO_DUPLICADO {
            get {
                return ResourceManager.GetString("SP_VALIDA_RECAUDO_DUPLICADO", resourceCulture);
            }
        }
    }
}
