//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corona.RecaudoPagos.DM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcedimientosAlmacenados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcedimientosAlmacenados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corona.RecaudoPagos.DM.Resources.ProcedimientosAlmacenados", typeof(ProcedimientosAlmacenados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CONSULTA_CLIENTE.
        /// </summary>
        internal static string SP_CONSULTA_CLIENTE {
            get {
                return ResourceManager.GetString("SP_CONSULTA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CONSULTA_SOCIEDAD.
        /// </summary>
        internal static string SP_CONSULTA_SOCIEDAD {
            get {
                return ResourceManager.GetString("SP_CONSULTA_SOCIEDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CONSULTA_USUARIO_ACCESO.
        /// </summary>
        internal static string SP_CONSULTA_USUARIO_ACCESO {
            get {
                return ResourceManager.GetString("SP_CONSULTA_USUARIO_ACCESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERTA_AUDITORIA.
        /// </summary>
        internal static string SP_INSERTA_AUDITORIA {
            get {
                return ResourceManager.GetString("SP_INSERTA_AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERTA_CLIENTE.
        /// </summary>
        internal static string SP_INSERTA_CLIENTE {
            get {
                return ResourceManager.GetString("SP_INSERTA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERTA_LOGREQUEST.
        /// </summary>
        internal static string SP_INSERTA_LOGREQUEST {
            get {
                return ResourceManager.GetString("SP_INSERTA_LOGREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERTA_RECAUDO.
        /// </summary>
        internal static string SP_INSERTA_RECAUDO {
            get {
                return ResourceManager.GetString("SP_INSERTA_RECAUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_VALIDA_RECAUDO_DUPLICADO.
        /// </summary>
        internal static string SP_VALIDA_RECAUDO_DUPLICADO {
            get {
                return ResourceManager.GetString("SP_VALIDA_RECAUDO_DUPLICADO", resourceCulture);
            }
        }
    }
}
